### PR TITLE
E1659 Refactor on_the_fly_calc.rb

### PR DESCRIPTION
**Pull request by aayushagarwal7**

### CODE REVIEW

**Comment by yangsong8** [comment]
Considered as final version of E1659. Will be checked later.

**Comment by yangsong8** [comment]
Has been merged, see 5fdb5fad9cdb03c9d931cab4aee461998da42f3b.
The pull request is still dirty, so I just grab your on_the_fly_calc.rb and replace the one on the master branch

**Comment by aayushagarwal7** [comment]
Thanks

**Comment by aayushagarwal7** [comment]
Hi Yang, we have even written test cases for this module, won't you be merging the test cases with master?

**Pull request closed without merging**
