### PR TITLE
E1641-refactor review mapping controller-part1

### PR DESCRIPTION
**Pull request by jdeng8**
This is a branch of our work, include part 1 refactor. We create two pull request because TA said that part 1 of our work needs to be paid attention to. The work exclude part one is in other pull request(pull request 821).

### CODE REVIEW

**Comment by yangsong8** [comment]
I have tested the changed code except automatic_review_mapping_strategy in this pull request. They look okay. Will keep you guys posted.

**Comment by Winbobob** [comment]
The test has already been merged, but I will do further modifications.

**Comment by Winbobob** [comment]
Currently, only test part of this pull request is merged.

**Comment by jdeng8** [comment]
Hi,
What do you mean by that? You need further consideration? Or our work is rejected?

**Pull request merged**
