### PR TITLE
E1866. Expertiza Internationalization

### PR DESCRIPTION
**Pull request by mukhtar23**
Please put the title of your pull request in the following format: *Project ID. Name*
for example, `[Project id/Independent study/Issue fix/...]. project name`, eg., `E904. Integrating courses and assignments on Expertiza with Moodle`

We suggest you include below information in your pull request:
- A description of the changes proposed in the pull request.
- @mentions of the person or team responsible for reviewing proposed changes.

Proposed Changes
- Adding dropdown in Edit Course to choose language for instructors
- Adding languages column to courses table
- Adding Hindi Language support for Expertiza

### CODE REVIEW

**Comment by Winbobob** [comment]
Hi team,

Please sync with the master branch. I just made some changes.

Thanks,
Zhewei

**Comment by mukhtar23** [comment]
How do i do this? I've looked online on how to merge it, but it's not
working

**Comment by mukhtar23** [comment]
Nvm. I got it

**Comment by Winbobob** [comment]
I tested on my local machine. This function occurs many bugs in student view, including omitting params id when switching to Hindi. So I cannot merge this pull request.

**Pull request closed without merging**
