### PR TITLE
E1905. Refactor questionnaires_controller.rb

### PR DESCRIPTION
**Pull request by vismay-golwala**
Modifications to the questionnaire controller:

- Removed `assign_instructor_id` method and replaced with logic from model
- Remove unused `export` and `import` methods and unused and commented out logic that referenced it.
- Created a method to reuse code for creating `QuizQuestionChoice`
- Moved `copy_questionnaire_details` to model

### CODE REVIEW

**Comment by jwarren3** [comment]
@vismay-golwala : Please change the title of the PR to:
`E1905. Refactor questionnaires_controller.rb`

and add the following changes:

- Remove `assign_instructor_id` method and replace with existing logic from user model.
- Remove unused export and import functions and unused and commented out logic that referenced it.

**Comment by dharmangbhavsar** [comment]
recheck

**Comment by dharmangbhavsar** [comment]
retest

**Comment by dharmangbhavsar** [comment]
test

**Comment by Winbobob** [comment]
Hi team,

Please [sync your branch to the Expertiza `beta` branch](https://help.github.com/en/articles/syncing-a-fork) and make `Travis CI` and `Code Climate` run on your pull request.

Thanks,
Zhewei

**Pull request merged**
