### PR TITLE
E1970. OSS project Oogie Boogie: User Experience & Confidence

### PR DESCRIPTION
**Pull request by YunkaiXiao**
We started working on the issue, this is the initial pull request to the beta branch. Previously we did a pull request to the master branch which I assume doesn't count.

### CODE REVIEW

**Comment by YunkaiXiao** [comment]
Issue #1467 is fixed

**Comment by YunkaiXiao** [comment]
Issue #1212 is fixed

**Comment by YunkaiXiao** [comment]
Issue #1312 Fixed

**Comment by johnbumgardner** [comment]
Schema file was deleted @YunkaiXiao Can you add the file?

**Comment by YunkaiXiao** [comment]
Just checked the original [commit history](https://github.com/expertiza/expertiza/pull/1534/commits/f0be5c43c834e38f7726cc6ee247f62fa1feb6d6) and expanded the last file (although marked as removed yet you could still expand/load diff to see the lines in that file). there seems to be no different than the [original 820-line schema file](https://github.com/expertiza/expertiza/blob/7e9507f8b9361112b41beec45d5aec1dc9bc54b5/db/schema.rb). Can't validate this, the EC2 instance I used to develop this 2 years ago was long gone.

**Pull request closed without merging**
