### PR TITLE
E1504 Refactoring the Bookmark model

### PR DESCRIPTION
**Pull request by manish211**

### CODE REVIEW

**Comment by ikopas** [comment]
We added a cucumber test and tried to send a pull request, but it seems that the request for these last two commits regarding the cucumber test have failed due to this error condition:

 Failed — The Travis CI build could not complete due to an error
This branch has failed checks, but can be merged.
Only those with write access to this repository can merge pull requests.

**Comment by yangsong8** [comment]
Hi, did you receive feedback from TAs on you OSS project? 

Our record says "They have to do extra work. The 'manage book marks' should not be a link on the top of the tree display, instead this function should be designed for each assignment."

This means you need to do extra work to make your pull request ready to merge.

**Comment by manish211** [comment]
@ikopas Adding Ivan to see this comment.

**Comment by manish211** [comment]
Hello @yangsong8 (Copying @ikopas as well ),
                   I just cross-checked the requirement document . This was not mentioned over there. Is this a new requirement or request?  The user interface was not there in the first place. When we started working, we realized that the user interface was not there only for the bookmarks. We have already put a lot of extra work in getting the user interface working for bookmark model so that we could test our code changes for the below requirement. Also, could you please elaborate and give some more details about the record that you mentioned?

I am pasting the contents of the document for your reference as below:

E1504. Refactoring the Bookmark model
Contact: Ed Gehringer, efg@ncsu.edu
Classes: 
What it will do:  This model adds bookmarks to the topics, edits them and allows the user to search based on the tags and the users.
What needs to be done:
Duplicate code in search_alltags_allusers, search_fortags_allusers, search_fortags_forusers, search_alltags_forusers. Needs to be separated out and written as a different method and can be called in all other methods.
Add_new_bookmark method should be renamed to create method
Method names add_topic_bookmark, add_this_bookmark, add_bookmark should be changed.
Method edit_this_bookmark should be renamed to edit
The methods add_bmapping, add_bmapping_signuptopic should be moved to bmapping as they belong to that class. Check the dependencies before moving the methods.

**Comment by ikopas** [comment]
Hello Mr. Song,

I hope that this email finds you doing well. We did receive feedback from a
TA, but the feedback did not include your comment regarding the "Manage
Bookmarks" hyperlink. We believe that this has been some sort of mistake
since we have closely followed the design document that has been given to
us and adding the "Manage bookmarks" link to each assignment was not one of
the requirements. Please find the list of the requirements for our project
in the document attached. Our tasks were related to refactoring the
bookmark model and we added the "Manage Bookmarks" link  to tree_list as an
extra feature only to make it easier for our peers to review our work.

Best,
Ivan

**Comment by yangsong8** [comment]
Hi everyone,

I was on the meeting to grade the OSS projects. At that time we wrote done that comment ("They have to do extra work. The 'manage book marks' should not be a link on the top of the tree display, instead this function should be designed for each assignment.") and I suppose that the TA should let you know. 

But you do not need to worry about your OSS grades too much (generally, the teaching staff is generous). I also understand that you guys are very busy at the end of semester. Of course the teaching staff will consider update your OSS grades if you re-design part of the functionality of your OSS project.

Thanks,

Yang

**Pull request closed without merging**
