### PR TITLE
E1813. Write unit tests for menu_item.rb

### PR DESCRIPTION
**Pull request by angad8292**
Added unit tests with 100% code coverage for menu_item.rb model

### CODE REVIEW

**Comment by angad8292** [comment]
Added comments for mapping test cases to wiki page

**Comment by angad8292** [comment]
Reduced unnecessary spaces

**Comment by Winbobob** [comment]
### General comments
- You did a good job of writing unit tests!
- Path coverage: 100%, MSI coverage: ___
- Please fix code climate issues as many as you can
### Issues

**Comment by Winbobob** [comment]
I partially merged your pull request, see 1cc8a263da8bda8f6245502398e69059088fbe4e.

**Pull request closed without merging**
