### PR TITLE
Assignment helper refactor

### PR DESCRIPTION
**Pull request by nnhimes**
Please set the title of your pull request in the following format: `[Project id/Independent study/Issue fix/...]. project name`, eg., `E904. Integrating courses and assignments on Expertiza with Moodle`

We suggest you including the below information in your pull request:
- A description of the changes proposed in the pull request.
- @mentions of the person or team responsible for reviewing proposed changes.
---
About Expertiza Bot
- If you have any questions about comments given by the expertiza-bot [(example)](https://github.com/expertiza/expertiza/pull/1877#issuecomment-762412918), you could create a comment in your pull request with the format `/dispute [UUID1] [UUID2]` [(example)](https://github.com/expertiza/expertiza/pull/1877#issuecomment-762430057) then the professor and TAs will be notified.
- [Here is a video](https://tinyurl.com/internet-bots) about how to communicate to expertiza-bot.

### CODE REVIEW

**Comment by nnhimes** [comment]
^ Changing autoload path didn't seem to make a difference. May want to revert this commit, but the new way is also cleaner

**Comment by nnhimes** [comment]
Helpers and models tests fixed, need to finish up controllers, lib test fixes

**Comment by nnhimes** [comment]
Only two errors in controllers remain, then manual testing on the environment can be done

**Comment by nnhimes** [comment]
All tests pass now, though I think the spec tests should be added to and looked at again in a future project. Would be a good project for 517. Will test on an environment now.

**Comment by nnhimes** [comment]
To test:

- Created a new assignment with teams
- Added two review rounds, and varied the rubric by round
- Added four participants: student7500-student7503
- Teamed student7500 and student7501 together, and student7502 & student7503 together
- Was able to review both rounds successfully. The second review was done as an update on the first round. The rubrics were different. 
- _Clicking your scores on the assignment gives "nil can't be coerced into Float" error on line 41 in view_team.html.erb.  However, clicking Alternate View appears. I am confused about it though, because some students have 2 reviews for the first round, but other have only 1. I thought everyone should have two reviews since they are on teams and I submit reviews for all four students._
image

- **After reviews were submitted in the second round I was able to get this page to work (need to have reviews done for both rounds first?)**
- _After it is over, clicking View Scores as the instructor creates this NoMethodError:_
 
image

- _Trying to view the Review Report gives this error:_
image

- The other report views work without error however
- Viewing submissions works and shows the teams as well

**Review by johnbumgardner — APPROVED** [review]
LGTM

**Pull request merged**
