### PR TITLE
Issue Fix: Pending Serveys tab cannot be found for ResponseController (for student account)/Test Coverage Increase for Survey Deployments Controller

### PR DESCRIPTION
**Pull request by johnbumgardner**
This is a fix for issue #1874 discovered by @kpiryani10 on the menu.

This is not a very DRY fix as pending_surveys method now exists in both survey_deployment_controller.rb and response_controller.rb, where the method in response_controller will just redirect to the other controller. 

Trying to increase test coverage on survey_deployments_controller.rb as well.

### CODE REVIEW

**Comment by johnbumgardner** [comment]
No change in behavior

**Comment by johnbumgardner** [comment]
Developing tests for the Survey Deployment Controller

**Comment by johnbumgardner** [comment]
Can you squash these commits when you merge them? @Saurabh110

**Comment by Saurabh110** [comment]
> Can you squash these commits when you merge them? @Saurabh110

Sure!

**Pull request merged**
