### PR TITLE
E2106. Fix view in student_task/list page

### PR DESCRIPTION
**Pull request by sharathKV**
Initial Changes done in app/views/student_task/list.html.erb:
Fix the ugly gap between two divs
Testing pull request

Team_3848 ECE 517 Spring 2021. Contributing team members:
Sharath Kumar: svkumar2
Nikhil Sundaraswamy: nsundar

Mentor: Saurabh Shingte

### CODE REVIEW

**Comment by Winbobob** [comment]
We do not require to write tests for UI changes.

**Comment by Winbobob** [comment]
Hi @sharathKV, please trigger the Travis CI again, then you should see the 2 warnings mentioned by the bot be cancelled.

**Comment by Nikhil1220** [comment]
Have added checkbox to the publishing rights column

**Pull request merged**
