### PR TITLE
E1510 Expertiza - Fix Instructor Login Performance Issue

### PR DESCRIPTION
**Pull request by fwu8**

### CODE REVIEW

**Comment by yangsong8** [comment]
Hi Fan,

Is this the code you currently deployed on http://152.46.16.86:3000/?

Thanks,

Yang

**Comment by fwu8** [comment]
Yes,this is my code.

**Comment by fwu8** [comment]
Hi Yang,

Is there any problem with this pull request? This is my OOS project, but it
it seems the previous pull request is rejected, and we do not get the
grade, and thus I make a pull request.

Best,
Fan

**Comment by yangsong8** [comment]
Hi Fan, no worries, I have merged part of your work from this pull request. I will meet with Dr .Gehringer on Monday and I will remind him to update your grade on OSS project.

Cheers,

Yang

**Comment by fwu8** [comment]
Oh! really thanks!

Sincerely,
WuFan

**Comment by fwu8** [comment]
Hi Yang,

Besides, we find that the previous database we received  from others has a
little problem, and this is why we cannot load the database correctly. We
reserve a new vcl and load the database in it: http://152.46.20.174:3000/ (
User Name: user6, no password). We also submit this in expertiza:
https://github.com/fwu8/expertiza-1, http://152.46.20.174:3000/. Thanks~

Best,
WuFan

**Pull request closed without merging**
