### PR TITLE
E1814. Write unit tests for collusion_cycle.rb

### PR DESCRIPTION
**Pull request by ZekunStevenZhang**
E1814 Unit Test for Collusion_Cycle.rb

### CODE REVIEW

**Comment by EthanMaNCSU** [comment]
E1814. Write unit tests for collusion_cycle.rb

**Comment by EthanMaNCSU** [comment]
E1814 Unit Test for Collusion_Cycle.rb

**Comment by EthanMaNCSU** [comment]
collusion_cycle_spec.rb

**Comment by Winbobob** [comment]
- Path coverage: 100%
- Please fix code climate issues as many as you can

**Pull request closed without merging**
