### PR TITLE
E1607. Functional tests for assignment creation function

### PR DESCRIPTION
**Pull request by panxing01**

### CODE REVIEW

**Comment by bghagar** [comment]
The rubygems file works on the testing end with the updates, but rubymine handled that for me. The Conflicts can be ignored, all code for the project itself have no merge errors.... up to you if you want to keep the updated gems as well. I don't think they are needed for the code to run.

**Comment by Winbobob** [comment]
When I merge your pull request, I will remove the conflicts. Now I am looking into the `DiagnosticMiddleware`.

**Comment by bghagar** [comment]
I just reverted the gemfile to match the main repo versions, hopefully the bundle install works now

**Comment by bghagar** [comment]
build fails on:
$ cp config/database.yml config/database.yml

if I put database.yml in the config directory it fails saying the file already exists. Not sure how to fix that.

**Comment by bghagar** [comment]
Oh. It runs the .travis script. Fixed.

**Comment by bghagar** [comment]
Downgrading to the version of capybara and selenium listed in the base breaks testing with selenium abover version 17 of firefox.... previously after letting rubymine handle updates version 45 was working. It passes the criteria for integration now though.

**Pull request closed without merging**
