### PR TITLE
E1526. Responsive web design for Expertiza 

### PR DESCRIPTION
**Pull request by p31-d3ng**
Responsive Design and AngularJS integration into Expertiza

### CODE REVIEW

**Comment by krunaljhaveri** [comment]
This pull request should not be merged currently in the Rails 4 branch since it has angular JS support for 3 main pages. We must work on this prototype further and than merge eventually. Any other suggestions appreciated too on how we can go about this pull request.

**Comment by p31-d3ng** [comment]
oh okay I will create a new pull-request to a new branch!

**Comment by yangsong8** [comment]
Hi Pei, you can pull all the new updates from Rails 4 branch to your forked repo. This link will help:https://help.github.com/articles/syncing-a-fork/. Since you guys did not change the files too much, there should not be big number of conflicts.

**Comment by p31-d3ng** [comment]
Hi Yang, the branch is updated with latest rails4 changes on the expertiza repo. Thanks!

**Comment by krunaljhaveri** [comment]
Please fix the travis build.  Simple errors come up.

**Pull request closed without merging**
