### PR TITLE
E1558. Refactoring ReviewResponseMap.rb 

### PR DESCRIPTION
**Pull request by adeeshag**

### CODE REVIEW

**Comment by yangsong8** [comment]
The response_map_controller.delete does not work. I can click "delete" on review_mapping/list_mappings page. The error message was "This review has already been done. It cannot been deleted.".
image

The response_map_controller.export does not work. I clicked "Export review mapping" then "Export" and got the message below:
image

Method self.find_assignment(id) in review_response_map.rb looks problematic.

Method self.get_assignment_participant in review_response_map.rb  looks problematic.

**Comment by adeeshag** [comment]
Hey Yang! Our code looks like this:

# options parameter used as a signature in other models
  def self.export(csv, parent_id, options)
    reviewed_object_maps = where(reviewed_object_id: parent_id)
    reviewed_object_maps = reviewed_object_maps.sort { |a, b| a.reviewee.name <=> b.reviewee.name }
    reviewed_object_maps.each do
    |map|
      csv << [map.reviewee.name, map.reviewer.name]
    end
  end

I'm not sure that you are testing the correct code given for this. Please let me know. Thanks!

**Comment by adeeshag** [comment]
We ran into issues when we used the .sort! method in our tests so we changed it to this. Please let us know if you still face any issues.

**Comment by yangsong8** [comment]
My question is, after your refactoring, is exporting response maps working? If you claim it works, you may come to my office, use my computer to pull the current version of your pull request and demonstrate it to me.

**Comment by adeeshag** [comment]
Yes it is working. Please find the following screen shots: 
screen shot 2015-12-09 at 9 48 17 pm
screen shot 2015-12-09 at 9 50 10 pm
screen shot 2015-12-09 at 9 50 22 pm
screen shot 2015-12-09 at 9 51 09 pm


Also, as for the delete part, that code is: 
def delete_reviewer
    review_response_map = ReviewResponseMap.find(params[:id])
    assignment_id = review_response_map.assignment.id
    if !Response.exists?(map_id: review_response_map.id)
        review_response_map.destroy
        flash[:success] = "The review mapping for \""+review_response_map.reviewee.name+"\" and \""+review_response_map.reviewer.name+"\" have been deleted."
    else
      flash[:error] = "This review has already been done. It cannot been deleted."
    end
    redirect_to :action => 'list_mappings', :id => assignment_id
  end

which is part of the review_mapping_controller.rb .
And our code changes were only for the ReviewResponseMap model. Hence, I don't think we were expected to look into that.

I can probably meet you only on 14th December (Monday) after which I will be traveling for the winter break. 

Thank you.

**Comment by yangsong8** [comment]
Yes you can come to my office at EB2 2271 to show me the export and import functions. How does 10:30 am sounds to you?

**Pull request closed without merging**
