### PR TITLE
E1837. refactoring review_mapping_controller.rb

### PR DESCRIPTION
**Pull request by dangoslen**
This PR include refactoring of the review_mapping_controllera as well as additional tests to validate those refactors.

At a high-level, this includes:
- Pulling raw SQL into models where possible
- Removing unused paths
  - POST response_report
- Ensuring that method names are consistent within the controller

Our team consisted of:
@dangoslen
@Suhas-Keerthiraju
@RamyaViju

Our mentor was @efg

### CODE REVIEW

**Comment by dangoslen** [comment]
@Winbobob many of the CodeClimate checks fail with "Cyclomatic Complexity". However, this is happening for algorithms already in place that we have simply re-located for better separation of concerns, but we did not want to mess with the algorithms themselves. Is there a requirement that all of these Code Climate checks pass?

**Comment by dangoslen** [comment]
We have had difficulty getting a port open in the firewall for our application in VCL. It runs on the local machine, however. I have a ticket with IT to help open the firewall, but they themselves had issues.

**Comment by dangoslen** [comment]
Also, expertiza won't accept a valid IP URL `http://152.46.16.106:8080` is our VCL host that, once the firewall issue is resolved, will show the running expertiza from our fork

**Comment by Winbobob** [comment]
> Also, expertiza won't accept a valid IP URL `http://152.46.19.24:3000/` is our VCL host that, once the firewall issue is resolved, will show the running expertiza from our fork

Try to restart the firewall service (`sudo ufw reload`) to see whether it works.

**Comment by Winbobob** [comment]
> "Cyclomatic Complexity"

You could ignore `Cyclomatic Complexity`.

HTH,
Zhewei

**Comment by Winbobob** [comment]
Wait for 2018 fall semester final project [E1868](https://github.com/expertiza/expertiza/pull/1307).

**Comment by efg** [comment]
This code is likely included in pull request #1307 so I am closing this pull request for now.  It will be merged when #1307 is merged.

**Pull request closed without merging**
