### PR TITLE
E2204: Testing for markup_styles_controller, lock_controller

### LINKED ISSUE #2304: Problem rendering the homepage
After first setting up the project, I get this error when try to access the home page (http://localhost:3000) 

image

### PR DESCRIPTION
**Pull request by dnguyenv**
- E2204: Testing for markup_styles_controller, lock_controller

### CODE REVIEW

**Review by hyeokjun-kwon — APPROVED** [review]
Should we add more test case?

**Comment by nnhimes** [comment]
Lock controller needs testing still. Also, please remove the extra files beyond the specs. I believe the bootstrap issue fix was merged into beta a few days ago

**Comment by dnguyenv** [comment]
Done. Thanks @nnhimes

**Comment by nnhimes** [comment]
Thanks. Please also remove the layout white space changes and the  .rspec file change. You should just have the two test files and the factory edits.

**Comment by dnguyenv** [comment]
@nnhimes Done

**Comment by nnhimes** [comment]
Please create a empty/comment commit so that Travis will be run on your build

**Comment by dnguyenv** [comment]
Done @nnhimes

**Pull request merged**
